### PR TITLE
Create 86crypto

### PR DESCRIPTION
**Pull request by TRYK86**

### CODE REVIEW

**Comment by yongbeam** [comment]
plz symbol image file

**Comment by yongbeam** [comment]
We will close this PR and register directly.

**Comment by yongbeam** [comment]
https://github.com/dexlab-project/assets/blob/master/tokens/solana/86/symbol.png?raw=true

**Comment by TRYK86** [comment]
OK.



Cheers.
RB.
TRYK.86.LLC
307.207.6057

**Pull request closed without merging**
